### ISSUE TITLE
Appeal to Authority

### ISSUE THREAD

**Issue by njkeng** [almossawi/badarguments#12]
I believe the section "Appeal to irrelevant authority" is, in some respects, incorrect.  The section confuses the concepts of "belief" and "truth".   It is reasonable to form a belief on the basis of authority, but appeal to authority of any kind is a logical fallacy. Nothing becomes true simply because someone says that it is. This ties in with the "genetic fallacy".  The final paragraph of the genetic fallacy section of the book demonstrates this exact point. Leading on from this, appeal to irrelevant authority is an unreasonable basis to form even a belief and such appeals are indeed bad arguments. I also believe it is incorrect to say that scientists typically appeal to authority.  It is wrong for a scientist to appeal to expert opinion and present this as fact. Scientists cite data and research.  It is the evidence alone that matters. 

My suggested re-wording is below.  Because I have introduced some new ideas, I have also shortened the piece in the hope that it still fits on a single page. I didn't go into any depth about the genetic fallacy.  There's a separate section dedicated to that.

Let me know what you think.

Suggested wording:
An appeal to authority is an appeal to one's sense of modesty [Engel], which is to say, an appeal to the feeling that others are more knowledgeable. While this is a comfortable and natural tendency for humans, such appeals cannot tell us which things are true and which are false.  All appeals to authority are a type of Genetic Fallacy; Experts do not have the characteristic of producing absolute truth.  To determine truth from untruth we must rely on evidence and reason.

However appeals to relevant authority can tell us which things are likely to be true.  This is the means by which we form beliefs. The overwhelming majority of the things that we believe in, such as atoms and the solar system, are on reliable authority, as are all historical statements, to paraphrase C. S. Lewis.

It is fallacious to form a belief when the appeal is to an authority who is not an expert on the issue at hand. A similar appeal worth noting is the appeal to vague authority, where an idea is attributed to a vague collective. For example, Professors in Germany showed such and such to be true. Another type of appeal to irrelevant authority is the appeal to ancient wisdom, where something is assumed to be true just because it was believed to be true some time ago. For example, Astrology was practiced by technologically advanced civilizations such as the Ancient Chinese. Therefore, it must be true. One might also appeal to ancient wisdom to support things that are idiosyncratic, or that may change with time. Such appeals need to weigh the evidence that is available to us in the present.

**Comment by almossawi** [comment]
Much better. Thank you 👍 

Updated and deployed: https://bookofbadarguments.com/index.html?page=14
