### ISSUE TITLE
css bug

### ISSUE THREAD

**Issue by 221V** [almossawi/badarguments#35]
hello!

there are some css bug on
https://bookofbadarguments.com/ru/?view=allpages

page 57 - no light background image here,
and we can not see black text on black background
https://i.imgur.com/DOEQwS0.png

browser - firefox

**Comment by almossawi** [comment]
Hi! I'm not able to repro that on my end. Which version of Firefox are you running? Do you see the same thing when you disable extensions?

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/980049/179371327-e97d2d76-2a62-4ce3-87b8-40a6ba469449.gif)

**Comment by 221V** [comment]
oh, sorry - i check again after clear cache - now all ok)
maybe that was some cache bug in firefox on linux)
